FROM python:3.12-slim-bookworm

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    build-essential

WORKDIR /app


RUN pip install torch torchvision torchaudio

RUN python -m ensurepip --upgrade

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY tts_engine tts_engine
COPY app.py app.py

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]