services:
  orpheus-tts:
    container_name: orpheus-fastapi
    build:
      context: .
      dockerfile: Dockerfile.cpu
    env_file:
      - .env
    volumes:
      - /mnt/nvme/llm-models/:/root/.cache/huggingface/hub
      - ./outputs:/app/outputs
    entrypoint: uvicorn app:app --host 0.0.0.0 --port 4242 --reload
    ports:
      - "4242:4242"
    develop:
      watch:
        - action: rebuild
          path: requirements.txt
        - action: sync
          path: tts_engine
          target: /app/tts_engine
        - action: sync
          path: app.py
          target: /app/app.py
